AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Yellow Card Backend Test - Transaction Service (SAM + LocalStack)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME: !Ref TransactionsTable
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: local
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: transactions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  TransactionDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: transaction-dlq

  TransactionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: transaction-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TransactionDLQ.Arn
        maxReceiveCount: 3


  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/healthCheck.ts
    Properties:
      Handler: healthCheck.handler
      Events:
        Health:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /health
            Method: GET

  CreateTransactionFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/createTransaction.ts
    Properties:
      Handler: createTransaction.handler
      Environment:
        Variables:
          QUEUE_URL: !Ref TransactionQueue
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionsTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt TransactionQueue.QueueName
      Events:
        CreateTransaction:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /transactions
            Method: POST

  GetTransactionFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/getTransaction.ts
    Properties:
      Handler: getTransaction.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TransactionsTable
      Events:
        GetTransaction:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /transactions/{id}
            Method: GET

  ProcessTransactionFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/processTransaction.ts
    Properties:
      Handler: processTransaction.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionsTable
      Events:
        TransactionQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt TransactionQueue.Arn
            BatchSize: 1


Outputs:
  ApiBaseUrl:
    Description: Base URL of the API Gateway endpoint
    Value: !Sub "http://localhost:4566/restapis/${Api}/local/_user_request_"
