AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Yellow Card Backend Test - Transaction Service (SAM + LocalStack)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME: !Ref TransactionsTable
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: local
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: transactions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH


  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/healthCheck.ts
    Properties:
      Handler: healthCheck.handler
      Events:
        Health:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /health
            Method: GET


Outputs:
  ApiBaseUrl:
    Description: Base URL of the API Gateway endpoint
    Value: !Sub "http://localhost:4566/restapis/${Api}/local/_user_request_"
